### ISSUE TITLE
Loging into multiple instances

### ISSUE THREAD

**Issue by antoniosos** [oschl-git/aperture-messenger#3]
It's possible to login to the same account on multiple instances of the app. This can result in unexpected behavior when viewing a message in a group that was sent from the other instance.
![IssueScreenshot](https://github.com/oschl-git/aperture-messenger/assets/67897276/94e8404a-2d2e-415d-9f1c-5a63b61c7265)
Okay it's not unexpected but it's there

**Comment by oschl-git** [comment]
This is working as intended.
