### ISSUE TITLE
Wrong invalid color number

### ISSUE THREAD

**Issue by antoniosos** [oschl-git/aperture-messenger#4]
It says the number for the color white is invalid.
![image](https://github.com/oschl-git/aperture-messenger/assets/67897276/07503d7d-1e08-4e48-8d5f-1dacc5c1810a)
![image](https://github.com/oschl-git/aperture-messenger/assets/67897276/1e2e34b8-c963-4002-a4b4-89766e0d3a6e)

**Comment by oschl-git** [comment]
Fixed! Thanks.

https://github.com/oschl-git/aperture-messenger/commit/f645f006a2a3ff2016a329325a93da9326a9c15e
